#! /bin/sh

set -e
. /etc/profile
here=$(readlink -f "$0" | xargs dirname)


# Main script.
case "$1" in
    openssl | perl | pyenv | yum)
        _helper_command="helper-$1"
        shift
        sh "${here}/${_helper_command}" $@
    ;;
    *)
        echo "Unknown option '$1'"
        exit 1
    ;;
esac

unset _helper_command
