#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)

# Defaults.
DEFAULT_OPENSSL_URL=https://www.openssl.org/source
DEFAULT_OPENSSL_PREFIX=/opt/openssl
DEFAULT_OPENSSL_VERSION=1.0.2


# Install function.
do_install() {

    _cwd=$(pwd)
    _tmp=/tmp

    _openssl_quiet=0
    _openssl_version="${DEFAULT_OPENSSL_VERSION}"

    # Parse arguments.
    while [ $# -gt 0 ]; do
        case "$1" in
            -q | --quiet)
                _openssl_quiet=1
            ;;
            -v | --version)
                shift
                _openssl_version="$1"
            ;;
            *)
                echo "Unknown option '$1'"
                exit 1
            ;;
        esac
        shift
    done

    _openssl_prefix="${DEFAULT_OPENSSL_PREFIX}/${_openssl_version}"

    # Install a recent Perl before.
    sh $here/perl-helper install

    if [ $_openssl_quiet -eq 0 ]; then
        echo " ---> Installing OpenSSL ${_openssl_version}..."
        echo "      ---> OpenSSL ${_openssl_version}: downloading..."
    fi
    cd ${_tmp}
    curl -s ${DEFAULT_OPENSSL_URL}/openssl-${_openssl_version}.tar.gz -O
    tar -xzf openssl-${_openssl_version}.tar.gz
    cd openssl-${_openssl_version}

    if [ $_openssl_quiet -eq 0 ]; then
        echo "      ---> OpenSSL ${_openssl_version}: configuring..."
    fi
    PATH=/opt/perl/bin:$PATH
    ./config --prefix=${_openssl_prefix} --openssldir=${_openssl_prefix}/ssl  \
            no-shared -fPIC >/dev/null 2>&1

    if [ $_openssl_quiet -eq 0 ]; then
        echo "      ---> OpenSSL ${_openssl_version}: building..."
    fi
    make >/dev/null 2>&1

    if [ $_openssl_quiet -eq 0 ]; then
        echo "      ---> OpenSSL ${_openssl_version}: installing..."
    fi
    make install_sw >/dev/null 2>&1

    if [ $_openssl_quiet -eq 0 ]; then
        echo "      ---> OpenSSL ${_openssl_version}: linking certificates..."
    fi
    if [ -d ${_openssl_prefix}/ssl ]; then
        rmdir ${_openssl_prefix}/ssl/certs
    else
        mkdir ${_openssl_prefix}/ssl
    fi
    ln -s /etc/pki/tls/certs ${_openssl_prefix}/ssl/certs
    ln -s /etc/pki/tls/cert.pem ${_openssl_prefix}/ssl/cert.pem

    if [ $_openssl_quiet -eq 0 ]; then
        echo "      ---> OpenSSL ${_openssl_version}: cleaning..."
    fi
    cd ..
    rm -rf openssl-${_openssl_version}
    rm -f openssl-${_openssl_version}.tag.gz
    cd ${_cwd}

    if [ $_openssl_quiet -eq 0 ]; then
        echo " ---> Done!..."
    fi

    unset _openssl_quiet
    unset _openssl_version
    unset _openssl_prefix

    # Uninstall Perl.
    sh $here/perl-helper remove

}


# Remove function.
do_remove() {

    _openssl_quiet=0
    _openssl_version="${DEFAULT_OPENSSL_VERSION}"

    # Parse arguments.
    while [ $# -gt 0 ]; do
        case "$1" in
            -q | --quiet)
                _openssl_quiet=1
            ;;
            -v | --version)
                shift
                _openssl_version="$1"
            ;;
            *)
                echo "Unknown option '$1'"
                exit 1
            ;;
        esac
        shift
    done

    _openssl_prefix="${DEFAULT_OPENSSL_PREFIX}/${_openssl_version}"

    if [ $_openssl_quiet -eq 0 ]; then
        echo " ---> Removing OpenSSL ${_openssl_version}..."
    fi
    rm -rf "${_openssl_prefix}"

    if [ $_openssl_quiet -eq 0 ]; then
        echo " ---> Done!..."
    fi

    unset _openssl_quiet
    unset _openssl_prefix
    unset _openssl_version

}


# Main script.
case "$1" in
    install)
        shift
        do_install $@
    ;;
    remove)
        shift
        do_remove $@
    ;;
    *)
        echo "Unknown option '$1'"
        exit 1
    ;;
esac
